version: '3.8'

volumes:
  test_volume:

services:
  postgres:
    image: postgres:latest
    container_name: npec
    volumes:
      - test_volume:/var/lib/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=npec
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
