version: '3.8'

volumes:
  test_volume:

services:
  postgres:
    image: mysql:8.0.33
    container_name: npec_db
    volumes:
      - /var/lib/npec/data
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: npce_root_1234
      MYSQL_DATABASE: npec
    command:
      - --collation-server=utf8mb4_general_ci
  redis:
    image: redis:7.0.11
    container_name: npec_redis
    ports:
      - "6379:6379"
