spring:
  datasource:
    url: jdbc:h2:~/npec
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
    ttl:
      access: 60
      refresh: 1210000

  main:
    allow-bean-definition-overriding: true

  h2:
    console:
      enabled: true
      path: /h2-console

  config:
    import: secret.yml
